package models;
// Generated 20.10.2020 14:34:14 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Client generated by hbm2java
 */
@Entity
@Table(name="client"
    ,catalog="user02"
)
public class Client extends User implements java.io.Serializable {

     private Set<Zakaz> zakazs = new HashSet<Zakaz>(0);

    public Client() {
    }
	    
    public Client(Set<Zakaz> zakazs) {
       this.zakazs = zakazs;
    }
       
@OneToMany(fetch=FetchType.LAZY, mappedBy="client")
    public Set<Zakaz> getZakazs() {
        return this.zakazs;
    }
    
    public void setZakazs(Set<Zakaz> zakazs) {
        this.zakazs = zakazs;
    }




}


