package models;
// Generated 20.10.2020 14:34:14 by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Clotchstorage generated by hbm2java
 */
@Entity
@Table(name="clotchstorage"
    ,catalog="user02"
)
public class Clotchstorage extends Storage implements java.io.Serializable {

     private Cloth cloth;
     private Float length;

    public Clotchstorage() {
    }

    public Clotchstorage(Cloth cloth, Float length) {
       this.cloth = cloth;
       this.length = length;
    }
   
    
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="idCloth")
    public Cloth getCloth() {
        return this.cloth;
    }
    
    public void setCloth(Cloth cloth) {
        this.cloth = cloth;
    }
    
    @Column(name="length", precision=12, scale=0)
    public Float getLength() {
        return this.length;
    }
    
    public void setLength(Float length) {
        this.length = length;
    }
}


