package models;
// Generated 20.10.2020 14:34:14 by Hibernate Tools 4.3.1


import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * Director generated by hbm2java
 */
@Entity
@Table(name="director"
    ,catalog="user02"
)
public class Director extends User implements java.io.Serializable {

    public Director() {
    }
    
}


