package models;
// Generated 20.10.2020 14:34:14 by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Furniturestorage generated by hbm2java
 */
@Entity
@Table(name="furniturestorage"
    ,catalog="user02"
)
public class Furniturestorage extends Storage implements java.io.Serializable {

     private Furniture furniture;
     private Long amount;

    public Furniturestorage() {
    }
    
    public Furniturestorage(Furniture furniture, Long amount) {
       this.furniture = furniture;
       this.amount = amount;
    }
   
    
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="idFurniture")
    public Furniture getFurniture() {
        return this.furniture;
    }
    
    public void setFurniture(Furniture furniture) {
        this.furniture = furniture;
    }

    @Column(name="amount")
    public Long getAmount() {
        return this.amount;
    }
    
    public void setAmount(Long amount) {
        this.amount = amount;
    }
}


