package models;
// Generated 20.10.2020 14:34:14 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Furniture generated by hbm2java
 */
@Entity
@Table(name="furniture"
    ,catalog="user02"
)
public class Furniture  implements java.io.Serializable {


     private int idFurniture;
     private String name;
     private String type;
     private String width;
     private String length;
     private Integer weight;
     private byte[] image;
     private Float cost;
     private Set<Furniturestorage> furniturestorages = new HashSet<Furniturestorage>(0);
     private Set<Izdeliefurniture> izdeliefurnitures = new HashSet<Izdeliefurniture>(0);

    public Furniture() {
    }

	
    public Furniture(int idFurniture) {
        this.idFurniture = idFurniture;
    }
    public Furniture(int idFurniture, String name, String type, String width, String length, Integer weight, byte[] image, Float cost, Set<Furniturestorage> furniturestorages, Set<Izdeliefurniture> izdeliefurnitures) {
       this.idFurniture = idFurniture;
       this.name = name;
       this.type = type;
       this.width = width;
       this.length = length;
       this.weight = weight;
       this.image = image;
       this.cost = cost;
       this.furniturestorages = furniturestorages;
       this.izdeliefurnitures = izdeliefurnitures;
    }
   
     @Id 

    
    @Column(name="idFurniture", unique=true, nullable=false)
    public int getIdFurniture() {
        return this.idFurniture;
    }
    
    public void setIdFurniture(int idFurniture) {
        this.idFurniture = idFurniture;
    }

    
    @Column(name="name", length=45)
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }

    
    @Column(name="type", length=45)
    public String getType() {
        return this.type;
    }
    
    public void setType(String type) {
        this.type = type;
    }

    
    @Column(name="width", length=45)
    public String getWidth() {
        return this.width;
    }
    
    public void setWidth(String width) {
        this.width = width;
    }

    
    @Column(name="length", length=45)
    public String getLength() {
        return this.length;
    }
    
    public void setLength(String length) {
        this.length = length;
    }

    
    @Column(name="weight")
    public Integer getWeight() {
        return this.weight;
    }
    
    public void setWeight(Integer weight) {
        this.weight = weight;
    }

    
    @Column(name="image")
    public byte[] getImage() {
        return this.image;
    }
    
    public void setImage(byte[] image) {
        this.image = image;
    }

    
    @Column(name="cost", precision=12, scale=0)
    public Float getCost() {
        return this.cost;
    }
    
    public void setCost(Float cost) {
        this.cost = cost;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="furniture")
    public Set<Furniturestorage> getFurniturestorages() {
        return this.furniturestorages;
    }
    
    public void setFurniturestorages(Set<Furniturestorage> furniturestorages) {
        this.furniturestorages = furniturestorages;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="furniture")
    public Set<Izdeliefurniture> getIzdeliefurnitures() {
        return this.izdeliefurnitures;
    }
    
    public void setIzdeliefurnitures(Set<Izdeliefurniture> izdeliefurnitures) {
        this.izdeliefurnitures = izdeliefurnitures;
    }




}


