package models;
// Generated 20.10.2020 14:34:14 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Izdelie generated by hbm2java
 */
@Entity
@Table(name="izdelie"
    ,catalog="user02"
)
public class Izdelie  implements java.io.Serializable {


     private int idIzdelie;
     private String name;
     private Float width;
     private Float length;
     private byte[] image;
     private String comment;
     private Set<Izdeliecloth> izdeliecloths = new HashSet<Izdeliecloth>(0);
     private Set<Izdeliefurniture> izdeliefurnitures = new HashSet<Izdeliefurniture>(0);
     private Set<Zakazizdelie> zakazizdelies = new HashSet<Zakazizdelie>(0);

    public Izdelie() {
    }

	
    public Izdelie(int idIzdelie) {
        this.idIzdelie = idIzdelie;
    }
    public Izdelie(int idIzdelie, String name, Float width, Float length, byte[] image, String comment, Set<Izdeliecloth> izdeliecloths, Set<Izdeliefurniture> izdeliefurnitures, Set<Zakazizdelie> zakazizdelies) {
       this.idIzdelie = idIzdelie;
       this.name = name;
       this.width = width;
       this.length = length;
       this.image = image;
       this.comment = comment;
       this.izdeliecloths = izdeliecloths;
       this.izdeliefurnitures = izdeliefurnitures;
       this.zakazizdelies = zakazizdelies;
    }
   
     @Id 

    
    @Column(name="idIzdelie", unique=true, nullable=false)
    public int getIdIzdelie() {
        return this.idIzdelie;
    }
    
    public void setIdIzdelie(int idIzdelie) {
        this.idIzdelie = idIzdelie;
    }

    
    @Column(name="name", length=45)
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }

    
    @Column(name="width", precision=12, scale=0)
    public Float getWidth() {
        return this.width;
    }
    
    public void setWidth(Float width) {
        this.width = width;
    }

    
    @Column(name="length", precision=12, scale=0)
    public Float getLength() {
        return this.length;
    }
    
    public void setLength(Float length) {
        this.length = length;
    }

    
    @Column(name="image")
    public byte[] getImage() {
        return this.image;
    }
    
    public void setImage(byte[] image) {
        this.image = image;
    }

    
    @Column(name="comment", length=100)
    public String getComment() {
        return this.comment;
    }
    
    public void setComment(String comment) {
        this.comment = comment;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="izdelie")
    public Set<Izdeliecloth> getIzdeliecloths() {
        return this.izdeliecloths;
    }
    
    public void setIzdeliecloths(Set<Izdeliecloth> izdeliecloths) {
        this.izdeliecloths = izdeliecloths;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="izdelie")
    public Set<Izdeliefurniture> getIzdeliefurnitures() {
        return this.izdeliefurnitures;
    }
    
    public void setIzdeliefurnitures(Set<Izdeliefurniture> izdeliefurnitures) {
        this.izdeliefurnitures = izdeliefurnitures;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="izdelie")
    public Set<Zakazizdelie> getZakazizdelies() {
        return this.zakazizdelies;
    }
    
    public void setZakazizdelies(Set<Zakazizdelie> zakazizdelies) {
        this.zakazizdelies = zakazizdelies;
    }




}


