package models;
// Generated 20.10.2020 14:34:14 by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Izdeliecloth generated by hbm2java
 */
@Entity
@Table(name="izdeliecloth"
    ,catalog="user02"
)
public class Izdeliecloth  implements java.io.Serializable {


     private int idIzdelieCloth;
     private Cloth cloth;
     private Izdelie izdelie;

    public Izdeliecloth() {
    }

	
    public Izdeliecloth(int idIzdelieCloth) {
        this.idIzdelieCloth = idIzdelieCloth;
    }
    public Izdeliecloth(int idIzdelieCloth, Cloth cloth, Izdelie izdelie) {
       this.idIzdelieCloth = idIzdelieCloth;
       this.cloth = cloth;
       this.izdelie = izdelie;
    }
   
     @Id 

    
    @Column(name="idIzdelieCloth", unique=true, nullable=false)
    public int getIdIzdelieCloth() {
        return this.idIzdelieCloth;
    }
    
    public void setIdIzdelieCloth(int idIzdelieCloth) {
        this.idIzdelieCloth = idIzdelieCloth;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="idCloth")
    public Cloth getCloth() {
        return this.cloth;
    }
    
    public void setCloth(Cloth cloth) {
        this.cloth = cloth;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="idIzdelie")
    public Izdelie getIzdelie() {
        return this.izdelie;
    }
    
    public void setIzdelie(Izdelie izdelie) {
        this.izdelie = izdelie;
    }




}


