package models;
// Generated 20.10.2020 14:34:14 by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Izdeliefurniture generated by hbm2java
 */
@Entity
@Table(name="izdeliefurniture"
    ,catalog="user02"
)
public class Izdeliefurniture  implements java.io.Serializable {


     private int idIzdelieFurniture;
     private Furniture furniture;
     private Izdelie izdelie;
     private String place;
     private Float widthX;
     private Float lengthY;
     private Float spinZ;
     private Integer amount;

    public Izdeliefurniture() {
    }

	
    public Izdeliefurniture(int idIzdelieFurniture) {
        this.idIzdelieFurniture = idIzdelieFurniture;
    }
    public Izdeliefurniture(int idIzdelieFurniture, Furniture furniture, Izdelie izdelie, String place, Float widthX, Float lengthY, Float spinZ, Integer amount) {
       this.idIzdelieFurniture = idIzdelieFurniture;
       this.furniture = furniture;
       this.izdelie = izdelie;
       this.place = place;
       this.widthX = widthX;
       this.lengthY = lengthY;
       this.spinZ = spinZ;
       this.amount = amount;
    }
   
     @Id 

    
    @Column(name="idIzdelieFurniture", unique=true, nullable=false)
    public int getIdIzdelieFurniture() {
        return this.idIzdelieFurniture;
    }
    
    public void setIdIzdelieFurniture(int idIzdelieFurniture) {
        this.idIzdelieFurniture = idIzdelieFurniture;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="idFurniture")
    public Furniture getFurniture() {
        return this.furniture;
    }
    
    public void setFurniture(Furniture furniture) {
        this.furniture = furniture;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="idIzdelie")
    public Izdelie getIzdelie() {
        return this.izdelie;
    }
    
    public void setIzdelie(Izdelie izdelie) {
        this.izdelie = izdelie;
    }

    
    @Column(name="place", length=45)
    public String getPlace() {
        return this.place;
    }
    
    public void setPlace(String place) {
        this.place = place;
    }

    
    @Column(name="widthX", precision=12, scale=0)
    public Float getWidthX() {
        return this.widthX;
    }
    
    public void setWidthX(Float widthX) {
        this.widthX = widthX;
    }

    
    @Column(name="lengthY", precision=12, scale=0)
    public Float getLengthY() {
        return this.lengthY;
    }
    
    public void setLengthY(Float lengthY) {
        this.lengthY = lengthY;
    }

    
    @Column(name="spinZ", precision=12, scale=0)
    public Float getSpinZ() {
        return this.spinZ;
    }
    
    public void setSpinZ(Float spinZ) {
        this.spinZ = spinZ;
    }

    
    @Column(name="amount")
    public Integer getAmount() {
        return this.amount;
    }
    
    public void setAmount(Integer amount) {
        this.amount = amount;
    }




}


