package models;
// Generated 20.10.2020 14:34:14 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.OneToOne;
import javax.persistence.PrimaryKeyJoinColumn;
import javax.persistence.Table;
import org.hibernate.annotations.GenericGenerator;
import org.hibernate.annotations.Parameter;

/**
 * Manager generated by hbm2java
 */
@Entity
@Table(name="manager"
    ,catalog="user02"
)
public class Manager extends User implements java.io.Serializable {

     private Set<Zakaz> zakazs = new HashSet<Zakaz>(0);

    public Manager() {
    }

    public Manager(Set<Zakaz> zakazs) {
       this.zakazs = zakazs;
    }
      
@OneToMany(fetch=FetchType.LAZY, mappedBy="manager")
    public Set<Zakaz> getZakazs() {
        return this.zakazs;
    }
    
    public void setZakazs(Set<Zakaz> zakazs) {
        this.zakazs = zakazs;
    }

}


