package models;
// Generated 20.10.2020 14:34:14 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Inheritance;
import javax.persistence.InheritanceType;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Storage generated by hbm2java
 */
@Entity
@Table(name="storage"
    ,catalog="user02"
)
@Inheritance (strategy = InheritanceType.JOINED)
abstract public class Storage  implements java.io.Serializable {


     private int idStorage;
     private Integer idStorager;
     private Set<Storager> storagers = new HashSet<Storager>(0);

    public Storage() {
    }

	
    public Storage(int idStorage) {
        this.idStorage = idStorage;
    }
    public Storage(int idStorage, Integer idStorager, Set<Storager> storagers) {
       this.idStorage = idStorage;
       this.idStorager = idStorager;
       this.storagers = storagers;
    }
   
     @Id 
     @GeneratedValue (strategy = GenerationType.IDENTITY)
    
    @Column(name="idStorage", unique=true, nullable=false)
    public int getIdStorage() {
        return this.idStorage;
    }
    
    public void setIdStorage(int idStorage) {
        this.idStorage = idStorage;
    }

    
    @Column(name="idStorager")
    public Integer getIdStorager() {
        return this.idStorager;
    }
    
    public void setIdStorager(Integer idStorager) {
        this.idStorager = idStorager;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="storage")
    public Set<Storager> getStoragers() {
        return this.storagers;
    }
    
    public void setStoragers(Set<Storager> storagers) {
        this.storagers = storagers;
    }

}


