package models;
// Generated 20.10.2020 14:34:14 by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToOne;
import javax.persistence.PrimaryKeyJoinColumn;
import javax.persistence.Table;
import org.hibernate.annotations.GenericGenerator;
import org.hibernate.annotations.Parameter;

/**
 * Storager generated by hbm2java
 */
@Entity
@Table(name="storager"
    ,catalog="user02"
)
public class Storager extends User implements java.io.Serializable {

     private Storage storage;

    public Storager() {
    }

    public Storager(Storage storage, User user) {
       this.storage = storage;
    }
        
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="idStorager")
    public Storage getStorage() {
        return this.storage;
    }
    
    public void setStorage(Storage storage) {
        this.storage = storage;
    }

}


