package models;
// Generated 20.10.2020 14:34:14 by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Inheritance;
import javax.persistence.InheritanceType;
import javax.persistence.OneToOne;
import javax.persistence.Table;
import org.hibernate.annotations.GenericGenerator;
import org.hibernate.annotations.GenericGenerators;

/**
 * User generated by hbm2java
 */
@Entity
@Table(name="user"
    ,catalog="user02"
)
@Inheritance (strategy = InheritanceType.JOINED)
abstract public class User  implements java.io.Serializable {


     private int idUser;
     private String login;
     private String password;
     private String firstName;
     private String lastName;
     private Integer phone;
     private String email;

    public User() {
    }

	
    public User(int idUser) {
        this.idUser = idUser;
    }
    
    public User(int idUser, String login, String password, String firstName, 
            String lastName, Integer phone, String email) {
       this.idUser = idUser;
       this.login = login;
       this.password = password;
       this.firstName = firstName;
       this.lastName = lastName;
       this.phone = phone;
       this.email = email;
    }
   
     @Id 
     @GeneratedValue (strategy = GenerationType.IDENTITY)
    
    @Column(name="idUser", unique=true, nullable=false)
    public int getIdUser() {
        return this.idUser;
    }
    
    public void setIdUser(int idUser) {
        this.idUser = idUser;
    }

    
    @Column(name="login", length=45)
    public String getLogin() {
        return this.login;
    }
    
    public void setLogin(String login) {
        this.login = login;
    }

    
    @Column(name="password", length=45)
    public String getPassword() {
        return this.password;
    }
    
    public void setPassword(String password) {
        this.password = password;
    }

    
    @Column(name="firstName", length=45)
    public String getFirstName() {
        return this.firstName;
    }
    
    public void setFirstName(String firstName) {
        this.firstName = firstName;
    }

    
    @Column(name="lastName", length=45)
    public String getLastName() {
        return this.lastName;
    }
    
    public void setLastName(String lastName) {
        this.lastName = lastName;
    }

    
    @Column(name="phone")
    public Integer getPhone() {
        return this.phone;
    }
    
    public void setPhone(Integer phone) {
        this.phone = phone;
    }

    
    @Column(name="email", length=45)
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }
}


