package models;
// Generated 20.10.2020 14:34:14 by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Zakazizdelie generated by hbm2java
 */
@Entity
@Table(name="zakazizdelie"
    ,catalog="user02"
)
public class Zakazizdelie  implements java.io.Serializable {


     private int idZakazIzdelie;
     private Izdelie izdelie;
     private Zakaz zakaz;
     private Integer amount;

    public Zakazizdelie() {
    }

	
    public Zakazizdelie(int idZakazIzdelie) {
        this.idZakazIzdelie = idZakazIzdelie;
    }
    public Zakazizdelie(int idZakazIzdelie, Izdelie izdelie, Zakaz zakaz, Integer amount) {
       this.idZakazIzdelie = idZakazIzdelie;
       this.izdelie = izdelie;
       this.zakaz = zakaz;
       this.amount = amount;
    }
   
     @Id 

    
    @Column(name="idZakazIzdelie", unique=true, nullable=false)
    public int getIdZakazIzdelie() {
        return this.idZakazIzdelie;
    }
    
    public void setIdZakazIzdelie(int idZakazIzdelie) {
        this.idZakazIzdelie = idZakazIzdelie;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="idIzdelie")
    public Izdelie getIzdelie() {
        return this.izdelie;
    }
    
    public void setIzdelie(Izdelie izdelie) {
        this.izdelie = izdelie;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="idZakaz")
    public Zakaz getZakaz() {
        return this.zakaz;
    }
    
    public void setZakaz(Zakaz zakaz) {
        this.zakaz = zakaz;
    }

    
    @Column(name="amount")
    public Integer getAmount() {
        return this.amount;
    }
    
    public void setAmount(Integer amount) {
        this.amount = amount;
    }




}


