package models;
// Generated 20.10.2020 14:34:14 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Zakaz generated by hbm2java
 */
@Entity
@Table(name="zakaz"
    ,catalog="user02"
)
public class Zakaz  implements java.io.Serializable {


     private int idZakaz;
     private Client client;
     private Manager manager;
     private String etap;
     private Float cost;
     private Set<Zakazizdelie> zakazizdelies = new HashSet<Zakazizdelie>(0);

    public Zakaz() {
    }

	
    public Zakaz(int idZakaz) {
        this.idZakaz = idZakaz;
    }
    public Zakaz(int idZakaz, Client client, Manager manager, String etap, Float cost, Set<Zakazizdelie> zakazizdelies) {
       this.idZakaz = idZakaz;
       this.client = client;
       this.manager = manager;
       this.etap = etap;
       this.cost = cost;
       this.zakazizdelies = zakazizdelies;
    }
   
     @Id 

    
    @Column(name="idZakaz", unique=true, nullable=false)
    public int getIdZakaz() {
        return this.idZakaz;
    }
    
    public void setIdZakaz(int idZakaz) {
        this.idZakaz = idZakaz;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="idClient")
    public Client getClient() {
        return this.client;
    }
    
    public void setClient(Client client) {
        this.client = client;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="idManager")
    public Manager getManager() {
        return this.manager;
    }
    
    public void setManager(Manager manager) {
        this.manager = manager;
    }

    
    @Column(name="etap", length=100)
    public String getEtap() {
        return this.etap;
    }
    
    public void setEtap(String etap) {
        this.etap = etap;
    }

    
    @Column(name="cost", precision=12, scale=0)
    public Float getCost() {
        return this.cost;
    }
    
    public void setCost(Float cost) {
        this.cost = cost;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="zakaz")
    public Set<Zakazizdelie> getZakazizdelies() {
        return this.zakazizdelies;
    }
    
    public void setZakazizdelies(Set<Zakazizdelie> zakazizdelies) {
        this.zakazizdelies = zakazizdelies;
    }




}


